### ISSUE TITLE
Can't get the zip at the end! (Chrome)

### ISSUE THREAD

**Issue by sgdc3** [nikisby/GBookDown#1]
I get the "Saving..." alert but after I press OK nothing happens.

Chrome 49.0.2623.54 beta-m (64-bit) with Tampermonkey

**Comment by uncle-vania** [comment]
Hi! I forgot to mention this script only works in Firefox without any problems..
Chrome doesn't support synchronous ajax calls from userscripts with Tampermonkey.
And I didn't manage to make the script work without them. So, please try Firefox :)

**Comment by nikisby** [comment]
Hi! I forgot to mention this script only works in Firefox without any problems..
Chrome doesn't support synchronous ajax calls from userscripts with Tampermonkey.
And I didn't manage to make the script work without them. So, please try Firefox :)

**Comment by sgdc3** [comment]
Done but got another issue xD

**Comment by sgdc3** [comment]
#2
