### ISSUE TITLE
Output images issue

### ISSUE THREAD

**Issue by sgdc3** [nikisby/GBookDown#2]
![010_pt9](https://cloud.githubusercontent.com/assets/8779252/13337805/dc65d598-dc1d-11e5-8bab-d513dc28cb6d.png)

**Comment by nikisby** [comment]
Oh wow. Do you get such images with all books?

**Comment by sgdc3** [comment]
Wait, i think i found the cause, let me check...

**Comment by sgdc3** [comment]
It happens sometimes if greasemonkey is enabled...

**Comment by nikisby** [comment]
Yeah, I just checked on some random book, got normal PNGs.
I thought Google invented some new way of protecting their books from saving.

**Comment by sgdc3** [comment]
This was the source:
https://books.google.com/books?id=pAg0BgAAQBAJ&pg=PT3&dq=una+storia+nella+storia&hl=it&sa=X&ved=0ahUKEwjn2srFh5TLAhWkO5oKHXgiBN0Q6AEIITAB

**Comment by sgdc3** [comment]
Can you try it? Just to be sure it's not my fault.

**Comment by nikisby** [comment]
Yeah, I will try it now.

**Comment by nikisby** [comment]
All good for me, got the first 33 pages with Tor: https://yadi.sk/d/o61w5gyxpWxeB

**Comment by sgdc3** [comment]
can you  download the entire book and send it to me with an email? (sgdc3.mail@gmail.com) I really need this file.

**Comment by nikisby** [comment]
You can do it youself, use Tor + Greasemonkey + this user script.

**Comment by sgdc3** [comment]
Ok thanks, i'll report back ;)

**Comment by sgdc3** [comment]
@nikisby Nope, tryed with tor brower but nothing changed... Any ideas?

**Comment by sgdc3** [comment]
(Tried also with another computer)

**Comment by sgdc3** [comment]
@nikisby I tried and retried with tor but nothing :( Can you send me the zip please? I really need this! :/

**Comment by nikisby** [comment]
Alright, I've downloaded 96 pages out of 141 max: 

The rest 45 will unblock in 2-7 days, then I'll try again.

But please don't ask for more, as this script is working perfectly and has already been downloaded 373 times. Only you have this issue, so it must be your local problem.

**Comment by sgdc3** [comment]
@nikisby Thank you ;)
